version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "80:80"
    networks:
      - app-net
    volumes:
      - '.:/var/www/html'
    depends_on:
      - mysql
  mysql:
    image: 'mysql/mysql-server:8.0'
    container_name: mysql
    ports:
        - '${FORWARD_DB_PORT:-3306}:3306'
    env_file: .env
    environment:
        MYSQL_ROOT_PASSWORD: '${database_default_password}'
        MYSQL_ROOT_HOST: '%'
        MYSQL_DATABASE: '${database_default_database}'
        MYSQL_USER: '${database_default_username}'
        MYSQL_PASSWORD: '${database_default_password}'
        MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
        - 'app-mysql:/var/lib/mysql'
    networks:
        - app-net
    healthcheck:
        test:
            - CMD
            - mysqladmin
            - ping
            - '-p${database_default_password}'
        retries: 3
        timeout: 5s
networks:
  app-net:
    driver: bridge
volumes:
  app-mysql:
    driver: local